SET @SQL = 'SELECT  '
		+ @chr + 'tvv.VKORG PLANT_CODE,cnam.NAME1 PLANT_NAME'
		+ @chr + ',bt.PARTNER SAP_CUSTOMER_CODE,bt.BPEXT CONNECT_CUSTOMER_CODE,bt.NAME_ORG1||bt.NAME_ORG2||bt.NAME_ORG3||bt.NAME_ORG4 CUSTOMER_NAME'
		+ @chr + ',adr.STREET ADDRESS1,adr.STR_SUPPL1 ADDRESS2,adr.STR_SUPPL2 ADDRESS3 ,adr.STR_SUPPL3 ADDRESS4,adr.LOCATION ADDRESS5,adr.CITY2 DISTRICT,adr.POST_CODE1 POST_CODE,adr.CITY1 CITY'
		+ @chr + ',kn.REGIO STATE_CODE,t5.BEZEI STATE_NAME,adr6.SMTP_ADDR,kn.LZONE TRANSPORTATION_ZONE_CODE,trp.VTEXT TRANSPORTATION_ZONE_NAME,kn.LOCCO MASTER_KM_BP'
		+ @chr + ',tvv.VKGRP REGION_CODE,TVG.BEZEI REGION_NAME,tvv.KDGRP INDUSTRY_SCALE_CODE,t51.KTEXT INDUSTRY_SCALE_NAME'
		+ @chr + ',tvv.VKBUR SALES_OFFICE_CODE,tvk.BEZEI SALES_OFFICE_NAME,kn.NIELS GRADE,kn.BRAN1 INDUSTRY_TYPE_CODE,idt.VTEXT INDUSTRY_TYPE_NAME'
	--+ @chr + ', * '

		+ @chr + ',(CASE WHEN IFNULL(bt.XDELE,'''') = '''' THEN ''ACTIVE'' WHEN IFNULL(bt.XDELE,'''') = ''X'' THEN ''INACTIVE''  END)XDELE '
    + @chr + ',b5.partner2 as CONT_PERSON_CODE'
    + @chr + ',b0.name_first as CONT_NAME1,b0.name_last as CONT_NAME2'
    + @chr + ',a2.tel_number as CONT_TEL_NUMBER1,a3.tel_number as CONT_TEL_NUMBER2,a6.smtp_addr as CONT_EMAIL'
    + @chr + ',ac.str_suppl1 as CONT_ADD1,ac.str_suppl2 as CONT_ADD2,ac.street as CONT_ADD3,ac.str_suppl3 as CONT_ADD4'
    + @chr + ',ac.city1 as CONT_CITY,ac.post_code1 as CONT_POST_CODE,ac.region as CONT_STATE_CODE,t5.bezei as  CONT_STATE_NAME'
    + @chr + ',ac.addrnumber as CONT_ADRNO,tb.TEXT30 RELATION_TYPE,t91.BEZ20 CONT_DEPARTMENT,t9.BEZ30 CONT_DESIGNATION'
		
		
		+ @chr + 'FROM SAPABAP1.BUT000 bt'
		+ @chr + 'LEFT JOIN SAPABAP1.KNA1 kn on kn.KUNNR=bt.PARTNER AND kn.MANDT=bt.CLIENT'
		+ @chr + 'LEFT JOIN SAPABAP1.ADRC adr on adr.ADDRNUMBER=kn.ADRNR and adr.CLIENT=bt.CLIENT'
		+ @chr + 'LEFT JOIN SAPABAP1.ADR6 adr6 on adr6.ADDRNUMBER=kn.ADRNR and adr6.CLIENT=bt.CLIENT'
		+ @chr + 'LEFT JOIN SAPABAP1.T005U t5 on t5.BLAND=kn.REGIO AND t5.SPRAS=''E'' AND t5.LAND1=''IN'' AND t5.MANDT=bt.CLIENT'
		+ @chr + 'LEFT JOIN SAPABAP1.TZONT trp on trp.ZONE1=kn.LZONE AND trp.LAND1=''IN'' AND trp.MANDT=bt.CLIENT'
		+ @chr + 'LEFT JOIN '
		+ @chr + '('
		+ @chr + 'SELECT tvv.VKORG, tvv.KUNNR , tvv.MANDT '
		+ @chr + ',MAX(KDGRP)KDGRP,MAX(VKGRP)VKGRP  '
		+ @chr + ',MAX(tvv.VKBUR)VKBUR '
		+ @chr + 'FROM SAPABAP1.KNVV tvv ' 
		+ @chr + 'WHERE 1 =1 AND IFNULL(AUFSD,'''')='''' '
		+ ISNULL(@Plant_Code, '')
		+ @chr + 'GROUP BY tvv.VKORG, tvv.KUNNR , tvv.MANDT ' 
		+ @chr + ')tvv on tvv.KUNNR=bt.PARTNER AND tvv.MANDT=bt.CLIENT'

		+ @chr + 'LEFT JOIN SAPABAP1.T001W cnam on cnam.WERKS=tvv.VKORG and cnam.MANDT=bt.CLIENT'
		+ @chr + 'LEFT JOIN SAPABAP1.TVGRT tvg on tvg.VKGRP=tvv.VKGRP AND tvg.SPRAS=''E'' AND tvg.MANDT=bt.CLIENT'
		+ @chr + 'LEFT JOIN SAPABAP1.T151T t51 on t51.KDGRP=tvv.KDGRP AND t51.SPRAS=''E'' AND t51.MANDT=bt.CLIENT'
		+ @chr + 'LEFT JOIN SAPABAP1.TVKBT tvk on tvk.VKBUR=tvv.VKBUR AND tvk.SPRAS=''E'' AND tvk.MANDT=bt.CLIENT'
		+ @chr + 'LEFT JOIN SAPABAP1.TBRCT idt on idt.BRACO=kn.BRAN1 AND idt.SPRAS=''E'' AND idt.MANDT=bt.CLIENT'
		
		+ @chr + 'LEFT JOIN '
		+ @chr + '('
		+ @chr + 'SELECT VKORG,KUNNR,MAX(ZDIS_KM)ZDIS_KM FROM SAPABAP1.ZQHDR WHERE ZSTATUS=''APPROVED'' GROUP BY VKORG,KUNNR'
		+ @chr + ')km on tvv.VKORG=km.VKORG AND km.KUNNR=bt.PARTNER'

		+ @chr + 'LEFT JOIN SAPABAP1.but051 as b5 on b5.PARTNER1 = bt.PARTNER and b5.CLIENT = bt.CLIENT'
		+ @chr + 'left outer join SAPABAP1.BUT050 as b50 on b50.PARTNER2 = b5.PARTNER2 and b5.PARTNER1 = b50.PARTNER1 AND b50.client = b5.client'
    + @chr + 'left join SAPABAP1.but000 as b0 on b0.partner = b5.partner2 and b0.client = b5.client'
    + @chr + 'left join SAPABAP1.adr2 a2 on a2.persnumber = b0.persnumber and a2.client = b5.client and a2.consnumber = ''001'''
    + @chr + 'left join SAPABAP1.adr2 a3 on a3.persnumber = b0.persnumber and a3.client = b5.client and a3.consnumber = ''002'''
    + @chr + 'left join SAPABAP1.adrc as ac on ac.addrnumber = a2.addrnumber and ac.client = b5.client'
    + @chr + 'left join SAPABAP1.adr6 as a6 on a6.addrnumber = ac.addrnumber and a6.client = b5.client AND a6.FLGDEFAULT = ''X'''
    + @chr + 'left join SAPABAP1.t005u t5u on t5u.bland=ac.region and t5u.spras=''E'' and t5u.land1=''IN'' and t5u.mandt=b5.client'
	+ @chr + 'left join SAPABAP1.TB905T as tb on tb.RELKIND = b50.RELKIND AND tb.SPRAS = ''E'' AND tb.CLIENT = b5.client'
	+ @chr + 'left join SAPABAP1.TB913 as t9 on t9.PAFKT = b5.PAFKT AND t9.CLIENT = b5.CLIENT and t9.SPRAS = ''E'''
	+ @chr + 'left join SAPABAP1.TB911 as t91 on t91.ABTNR = b5.ABTNR and t91.CLIENT = b5.CLIENT and t91.SPRAS = ''E'''
