USE [SAPCONNECT]
GO
/****** Object:  StoredProcedure [dbo].[SAP_VENDOR_TRIAL_BALANCE]    Script Date: 02-07-2024 17:36:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SAP_VENDOR_TRIAL_BALANCE]
(
 @COMPANY VARCHAR(MAX) = '%'
 ,@PLANT VARCHAR(MAX) = '%'
 ,@FROM_DATE DATETIME
 ,@TO_DATE DATETIME
 ,@GLACCNO VARCHAR(500)=  '%'
 )
AS

BEGIN


--SAP_VENDOR_TRIAL_BALANCE '11','1102','20190401','20200331','0000130010'

DECLARE @GLACCNO1 Varchar(50)
SELECT @GLACCNO1=@GLACCNO

IF @GLACCNO IN ('ALL' ,'','%','''')
	BEGIN
		SET @GLACCNO=NULL
	END	
ELSE 
	SELECT @GLACCNO = ' AND ''' + @GLACCNO + ''' LIKE ''%'' || NULLIF(RACCT ,'''') || ''%'' '


DECLARE @PLANT1 Varchar(50)
SELECT @PLANT1=@PLANT


IF @PLANT IN ('ALL' ,'','%','''')
	BEGIN
		SET @PLANT=NULL
	END	
ELSE
	SELECT @PLANT = ' AND ''' + @PLANT + ''' LIKE ''%'' || NULLIF(LEFT(PRCTR,4) ,'''') || ''%'' '



DECLARE @SQL AS VARCHAR(MAX)

SELECT @SQL = '
SELECT 
	MAX(IFNULL(A.RBUKRS,B.RBUKRS)) COMPANY
	,(Case when ''' + @PLANT1 + '''=''%'' or ''' + @PLANT1 + '''=''ALL''  then '''' else ''' + @PLANT1 + ''' end) PLANT
	,Max(IFNULL(P.NAME1,''''))PLANTNAME
	,K.LIFNR VENDOR
	,MAX(C.NAME1||''''||C.NAME2||''''||C.NAME3) VENDORNAME
	,MAX(ADR.STREET) ADDRESS1
	,MAX(ADR.STR_SUPPL1) ADDRESS2
	,MAX(ADR.STR_SUPPL2) ADDRESS3 
	,MAX(ADR.STR_SUPPL3) ADDRESS4
	,MAX(ADR.LOCATION) ADDRESS5
	,MAX(ADR.CITY2) DISTRICT
	,MAX(ADR.POST_CODE1) POST_CODE
	,MAX(ADR.CITY1) CITY
	,MAX(C.REGIO) VENDORSTATECODE
	,MAX(T5.BEZEI)  VENDORSTATE_NAME
	,MAX(IFNULL(C.stcd3,'''')) VENDORGSTNUMBER
	,MAX(ifnull(C.J_1IPANNO,'''')) VENDORPANNO
	,IFNULL(B.OPNAMT,0.00)OPENINGAMOUNT
	,SUM((CASE WHEN A.HSL>0 THEN A.HSL ELSE 0.00 END))DEBITAMOUNT
	,ABS(SUM((CASE WHEN A.HSL<0 THEN A.HSL ELSE 0.00 END)))CREDITAMOUNT
	,IFNULL(B.OPNAMT,0.00)+SUM((CASE WHEN A.HSL>0 THEN A.HSL ELSE 0.00 END))-ABS(SUM((CASE WHEN A.HSL<0 THEN A.HSL ELSE 0.00 END)))BALANCE
	,TO_CHAR(AC.LAST_TRAN_DAT,''DD/MM/YYYY'')LAST_TRAN_DATE
	,K.AKONT RECON_ACCOUNT
	,G.TXT50 RECON_ACCOUNT_NAME
	,''' + @GLACCNO1 + ''' GL_ACCOUNT_NO
	,MAX(GA.TXT50) GL_ACCOUNT_NAME
 FROM SAPABAP1.LFB1 K
	LEFT JOIN SAPABAP1.LFA1 C ON K.LIFNR=C.LIFNR
	LEFT JOIN SAPABAP1.ADRC ADR ON ADR.ADDRNUMBER=C.ADRNR
	LEFT JOIN SAPABAP1.BUT000 M ON C.LIFNR=M.PARTNER
	LEFT JOIN  SAPABAP1.T005U t5 on t5.BLAND=C.REGIO AND t5.SPRAS=''E'' AND t5.LAND1=''IN'' AND t5.MANDT=900
	LEFT JOIN (SELECT *
		FROM SAPABAP1.ACDOCA WHERE BELNR NOT LIKE ''B%'' AND KOART=''K'' 
		' + ISNULL(@PLANT, ' ') + '
		AND BUDAT BETWEEN '''+CONVERT(VARCHAR(10),@FROM_DATE,112)+'''  AND '''+CONVERT(VARCHAR(10),@TO_DATE,112)+'''
		' + ISNULL(@GLACCNO, ' ') + ' )A ON K.LIFNR=A.LIFNR AND A.RBUKRS=K.BUKRS 
	LEFT JOIN 
		(SELECT	RBUKRS,LIFNR,IFNULL(SUM(HSL),0.00) OPNAMT  	
  			FROM SAPABAP1.ACDOCA WHERE BELNR NOT LIKE ''B%'' AND KOART=''K'' 
			' + ISNULL(@PLANT, ' ') + '
			AND BUDAT<'''+CONVERT(VARCHAR(10),@FROM_DATE,112)+''' 
			' + ISNULL(@GLACCNO, ' ') + '  
			GROUP BY LIFNR,RBUKRS)B ON K.LIFNR=B.LIFNR AND K.BUKRS=B.RBUKRS

	LEFT JOIN (SELECT MAX(BUDAT)LAST_TRAN_DAT,RBUKRS,LIFNR
		FROM SAPABAP1.ACDOCA WHERE BELNR NOT LIKE ''B%'' AND KOART=''K'' 
		' + ISNULL(@PLANT, ' ') + '
		AND BLART NOT IN (''AB'') 
		' + ISNULL(@GLACCNO, ' ') + '  
		GROUP BY RBUKRS,LIFNR)AC ON K.LIFNR=AC.LIFNR AND AC.RBUKRS=K.BUKRS 
		
		
	LEFT JOIN SAPABAP1.T001W P ON P.WERKS=''' + @PLANT1 + '''
	LEFT JOIN (SELECT * FROM SAPABAP1.SKAT WHERE KTOPL=''LGIN'') G ON K.AKONT=G.SAKNR
	LEFT JOIN (SELECT * FROM SAPABAP1.SKAT WHERE KTOPL=''LGIN'') GA ON GA.SAKNR=''' + @GLACCNO1 + '''
WHERE 
	 K.BUKRS LIKE '''+ @COMPANY + '''
	
	
GROUP BY
	K.LIFNR
	,B.OPNAMT
	,AC.LAST_TRAN_DAT
	,K.AKONT 
	,G.TXT50 

HAVING (IFNULL(B.OPNAMT,0.00)<>0 OR SUM((CASE WHEN A.HSL>0 THEN A.HSL ELSE 0.00 END))<>0  OR ABS(SUM((CASE WHEN A.HSL<0 THEN A.HSL ELSE 0.00 END)))<>0)
ORDER BY K.LIFNR

 '
PRINT(@SQL)
EXEC (@SQL) AT SAP_GHP

END






