USE [SAPCONNECT]
GO
/****** Object:  StoredProcedure [dbo].[SAP_FIXED_ASSET_ANALYSIS]    Script Date: 02-07-2024 19:30:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SAP_FIXED_ASSET_ANALYSIS]
	(
	@COMPANY VARCHAR(10)
	,@FROM_DATE DATETIME
	,@TO_DATE DATETIME
	,@ASSETNO VARCHAR(MAX)=''
	)
AS
--SAP_FIXED_ASSET_ANALYSIS '12','20220401','20230331','002020500002'

IF @COMPANY IN ('','0','%','''','ALL')
	BEGIN
		SET @COMPANY='%'
	END

IF @ASSETNO IN ('','0','%','''','ALL')
	BEGIN
		SET @ASSETNO=NULL
	END
ELSE 
	SELECT @ASSETNO = ' AND ''' + @ASSETNO + ''' LIKE ''%'' || NULLIF(K.FIXEDASSET ,'''') || ''%'' '

DECLARE @SQL AS VARCHAR(MAX)
DECLARE @SQL1 AS VARCHAR(MAX)
DECLARE @SQL2 AS VARCHAR(MAX)

SELECT @SQL = 
		'
SELECT 
		K.COMPANY
		,K.PLANT
		,K.PLANTNAME
		,K.FISCALYEAR
		,K.FIXEDASSET
		,K.FIXEDASSETNAME
		,K.ACCOUNTGROUP
		,K.ACCOUNTGROUPNAME
		,K.VENDORCODE
		,K.VENDORNAME
		,K.VENDORGSTNUMBER
		,K.GSTVENDORTYPE
		,K.VENDORSTATECODE
		,K.ORDERNO
		,K.ORDERDATE
		,K.MATERIALDOCTYPE
		,K.MATERIALDOCNO
		,K.SERVICEENTRYNO
		,K.FIMATERIALDOCNO
		,K.FIMMDOCYEAR
		,K.MATERIALPOSTINGDATE
		,K.DOCUMENTTYPE
		,K.DOCUMENTTYPEDESC
		,K.INVOICENO
		,K.FIINVOICENO
		,K.BILLDATE
		,K.POSTINGDATE
		,K.BILLNO
		,K.PURCHASETYPE
		,K.TYPE
		,K.DESCRIPTION
		,K.UOM
		,K.QUANTITY
		,CAST((CASE WHEN K.MATERIALDOCTYPE=''WE'' THEN (K.SETTLEMENTAMOUNT/K.QUANTITY) ELSE  K.UNITCOST END)AS NUMERIC(15,2))UNITCOST
		,K.SETTLEMENTAMOUNT
		,K.INVOICEAMT
		,K.TAXCODE
		,K.TAXCODEDESC
		,K.GSTRATE
		,K.TOTALGST
		,K.SETTLEMENTNO
		,K.NETWORK
		,K.NETWORKNAME
		,K.ACTIVITY
		,K.ACTIVITYNAME
		,K.ACCOUNTASSIGNMENT
		,K.WBSELEMENT
		,K.WBSELEMENTNAME
		,K.POSID
		,K.REMARK
		,K.SHORTTEXT
		,K.ANBWA
FROM

(
SELECT  
		A.RBUKRS COMPANY
		,A.WERKS PLANT
		,PA.NAME1 PLANTNAME
		,A.GJAHR FISCALYEAR
		,(CASE WHEN  IFNULL(CB.ANLN1,'''')='''' AND IFNULL(CN.ANLN1,'''')<>'''' THEN IFNULL(CN.ANLN1,'''') ELSE IFNULL(IFNULL(CB.ANLN1,CM.ANLN1),KA.ANLN1)   END) FIXEDASSET
		,IFNULL(FI.TXT50,'''') FIXEDASSETNAME
		,FI.KTOGR ACCOUNTGROUP
		,TA.KTGRTX ACCOUNTGROUPNAME
		,IFNULL(H.LIFNR,A.LIFNR) VENDORCODE
		,IFNULL((V.NAME1||''''||V.NAME2),'''')VENDORNAME
		,IFNULL(D.TAXNUM,'''') VENDORGSTNUMBER
		,(CASE WHEN V.VEN_CLASS = '''' THEN ''REGISTERED'' ELSE
		 (CASE WHEN V.VEN_CLASS =''0'' THEN ''UNREGISTERED'' ELSE '''' END)END) GSTVENDORTYPE
		,IFNULL(H.PLC_SUP,'''') VENDORSTATECODE
		,IFNULL(L.EBELN,A.EBELN) ORDERNO
		--,IFNULL(L.EBELP,A.EBELP) ORDERLINENO
		,IFNULL(TO_CHAR(EK.BEDAT,''DD-MON-YYYY''),'''')ORDERDATE
		,A.BLART MATERIALDOCTYPE
		,IFNULL(M.MBLNR,A.AWREF) MATERIALDOCNO
		,IFNULL((CASE WHEN M.LFBNR LIKE ''5%'' THEN '''' ELSE M.LFBNR END),'''') SERVICEENTRYNO
		,A.BELNR FIMATERIALDOCNO
		--,A.AWITEM FIMMDOCLINE
		,A.AWORG FIMMDOCYEAR
		,TO_CHAR(IFNULL(A.BUDAT,''''),''DD-MON-YYYY'') MATERIALPOSTINGDATE
		,IFNULL(A.BUDAT,'''')MATERIALPOSTDATE
		,(CASE WHEN H.XRECH='''' AND H.TCODE=''MIR7''  THEN ''KG'' ELSE
		 (CASE WHEN H.XRECH='''' AND H.TCODE<>''MIR7''  THEN ''RS'' ELSE IFNULL(B.BLART,'''') END)END) DOCUMENTTYPE

		,(CASE WHEN  H.XRECH<>'''' AND H.TCODE=''MIR7'' THEN ''MM INVOICE''	 ELSE
		 (CASE WHEN  H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ''REVERSE INVOICE''	ELSE IFNULL(B.BLART,'''') END)END)DOCUMENTTYPEDESC
		,IFNULL(H.BELNR,'''') INVOICENO
		,IFNULL(B.BELNR,'''') FIINVOICENO
		,IFNULL(TO_VARCHAR(H.BLDAT,''DD-MON-YYYY''),'''')  BILLDATE
		,IFNULL(TO_VARCHAR(H.BUDAT,''DD-MON-YYYY''),'''') POSTINGDATE
		,IFNULL(H.XBLNR,'''') BILLNO
		,(CASE WHEN IFNULL(L.MATNR,A.MATNR)<>'''' THEN ''GOODS'' ELSE
		 (CASE WHEN IFNULL(RB.ANLN1,'''')<>'''' THEN ''CAPITAL GOODS'' ELSE
		 (CASE WHEN IFNULL(RB.SAKNR,'''')<>'''' OR IFNULL(S.SERVICENO,'''')<>'''' THEN ''SERVICE '' ELSE ''''END)END)END)PURCHASETYPE
		,(CASE WHEN IFNULL(L.MATNR,A.MATNR)<>'''' THEN ''ITEM'' ELSE
		 (CASE WHEN IFNULL(RB.SAKNR,'''')<>'''' AND IFNULL(RB.ANLN1,'''')='''' OR IFNULL(S.SERVICENO,'''')<>'''' THEN ''GL'' ELSE
		 (CASE WHEN IFNULL(RB.ANLN1,'''')<>'''' THEN ''FIXED ASSET'' ELSE '''' END)END)END) TYPE
		,(CASE WHEN IFNULL(L.MATNR,A.MATNR)<>'''' THEN IFNULL(T.MAKTX,'''') ELSE
		 (CASE WHEN IFNULL(RB.SAKNR,'''')<>'''' AND IFNULL(RB.ANLN1,'''')='''' OR IFNULL(S.SERVICENO,'''')<>'''' THEN IFNULL(G.TXT50,'''') ELSE
		 (CASE WHEN IFNULL(RB.ANLN1,'''')<>''''  THEN IFNULL(FA.MCOA1,'''') ELSE '''' END)END)END) DESCRIPTION
		,IFNULL(IFNULL(U.MSEHL,SU.MSEHL),A.RUNIT) UOM
		,IFNULL((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' THEN (CASE WHEN L.MENGE=''0'' THEN 1 ELSE L.MENGE END)*-1 ELSE (CASE WHEN L.MENGE=''0'' THEN 1 ELSE L.MENGE END) END),A.MSL) QUANTITY
		,IFNULL((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' THEN IFNULL(IFNULL(PR.PREIS,S.RATE),PO.NETPR)*-1 ELSE IFNULL(IFNULL(PR.PREIS,S.RATE),PO.NETPR) END),A.HPVPRS) UNITCOST
		,(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' THEN A.HSL*-1 ELSE A.HSL END)  SETTLEMENTAMOUNT
		,IFNULL(L.WRBTR,0.00) INVOICEAMT
		,IFNULL(GS.TAXCODE,'''')TAXCODE
		,IFNULL(GS.TAXCODEDESC,'''')TAXCODEDESC
		,CAST(IFNULL(GS.GSTRATE,0.00) AS NUMERIC(18,3))GSTRATE
		,(CASE WHEN
				 ((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.CGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.CGSTAMOUNT,0.00) END)+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.SGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.SGSTAMOUNT,0.00) END) +(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.IGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.IGSTAMOUNT,0.00) END))=0 AND 
				((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMCGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMCGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMSGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMSGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMIGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMIGSTAMOUNT,0.00)) END))=0
			THEN 
				(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.NDCGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.NDCGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.NDSGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.NDSGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN  ABS(IFNULL(GS.NDIGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.NDIGSTAMOUNT,0.00)) END)
			 ELSE 
			 (CASE WHEN 
				((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.CGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.CGSTAMOUNT,0.00) END)+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.SGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.SGSTAMOUNT,0.00) END) +(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.IGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.IGSTAMOUNT,0.00) END))<>0 THEN 
				(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.CGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.CGSTAMOUNT,0.00) END)+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.SGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.SGSTAMOUNT,0.00) END) +(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.IGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.IGSTAMOUNT,0.00) END) ELSE
			 (CASE WHEN 
				((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMCGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMCGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMSGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMSGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMIGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMIGSTAMOUNT,0.00)) END)) <>0 THEN 
				((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMCGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMCGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMSGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMSGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMIGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMIGSTAMOUNT,0.00)) END))
			 ELSE 0 END)END)END) TOTALGST
		,A.CO_BELNR SETTLEMENTNO
		,IFNULL(ME.NPLNR,A.NPLNR) NETWORK
		,IFNULL(PN.KTEXT,'''') NETWORKNAME
		,IFNULL(AF.VORNR,A.NPLNR_VORGN) ACTIVITY
		,IFNULL(AF.LTXA1,AM.LTXA1) ACTIVITYNAME
		,A.ACCAS ACCOUNTASSIGNMENT
		,IFNULL(WB.POSKI,WM.POSKI) WBSELEMENT
		,IFNULL(WB.POST1,WM.POST1) WBSELEMENTNAME
		,IFNULL((CASE WHEN IFNULL(WB.POSID,'''')='''' THEN (CASE WHEN A.MAT_PS_POSID='''' THEN MN.MAT_PS_POSID ELSE A.MAT_PS_POSID END)  ELSE IFNULL(WB.POSID,'''') END),'''')POSID
		,A.SGTXT REMARK
		,EP.TXZ01 SHORTTEXT
		,A.ANBWA
FROM SAPABAP1.ACDOCA A
	LEFT JOIN SAPABAP1.EKPO EP ON EP.BUKRS=A.RBUKRS AND EP.EBELN=A.EBELN AND EP.EBELP=A.EBELP
	LEFT JOIN SAPABAP1.EKKO EK ON EK.BUKRS=A.RBUKRS AND EK.EBELN=A.EBELN
	LEFT JOIN SAPABAP1.T001W PA ON PA.WERKS=A.WERKS
	LEFT JOIN SAPABAP1.NSDM_V_MSEG M ON  M.EBELN=A.EBELN AND M.EBELP=A.EBELP AND A.AWORG=M.MJAHR AND A.AWREF=M.MBLNR AND A.AWITEM=''00''||''''||M.URZEI
	LEFT JOIN (SELECT * FROM SAPABAP1.EKBE WHERE BEWTP IN (''Q'',''T'')) EKA ON M.EBELN=EKA.EBELN AND M.EBELP=EKA.EBELP AND M.LFBJA=EKA.LFGJA AND M.LFBNR=EKA.LFBNR AND M.LFPOS=EKA.LFPOS
	LEFT JOIN (SELECT * FROM SAPABAP1.RBKP WHERE RBSTAT=''5'') H ON H.BELNR=EKA.BELNR AND H.GJAHR=EKA.GJAHR
	LEFT JOIN (SELECT * FROM SAPABAP1.BKPF WHERE BLART=''RE'') B ON LEFT(B.AWKEY,10)=H.BELNR AND B.GJAHR=H.GJAHR	
	LEFT JOIN SAPABAP1.RSEG L ON H.BUKRS=L.BUKRS AND H.BELNR=L.BELNR AND H.GJAHR=L.GJAHR AND M.EBELN=L.EBELN AND M.EBELP=L.EBELP AND M.LFBJA=L.LFGJA AND M.LFBNR=L.LFBNR AND M.LFPOS=L.LFPOS
	LEFT JOIN (SELECT DISTINCT MANDT,BUKRS,WERKS,AUFPL,APLZL,EBELN,EBELP,NPLNR,PS_PSP_PNR FROM SAPABAP1.NSDM_V_MSEG) ME ON  ME.EBELN=L.EBELN AND ME.EBELP=L.EBELP
	LEFT JOIN SAPABAP1.AFVC AF ON  AF.AUFPL=ME.AUFPL AND AF.APLZL=ME.APLZL AND AF.MANDT=ME.MANDT AND AF.BUKRS=ME.BUKRS AND AF.WERKS=ME.WERKS
	LEFT JOIN SAPABAP1.M_AUKOB PN ON PN.AUFNR=IFNULL(ME.NPLNR,A.NPLNR)
	LEFT JOIN SAPABAP1.PRPS WB ON WB.PSPNR=(CASE WHEN IFNULL(AF.PROJN,'''')='''' THEN ME.PS_PSP_PNR ELSE AF.PROJN END)
	LEFT JOIN (SELECT * FROM SAPABAP1.COBRB WHERE ANLN1<>'''' AND  GBISJ=''0000'') CB ON CB.MANDT=(CASE WHEN IFNULL(AF.PROJN,'''')='''' THEN WB.MANDT ELSE AF.MANDT END)  AND CB.OBJNR=(CASE WHEN IFNULL(AF.PROJN,'''')=''''   THEN WB.OBJNR ELSE AF.OBJNR END) AND H.GJAHR=CB.LETJA

	LEFT JOIN (SELECT * FROM SAPABAP1.COBRB WHERE ANLN1<>'''' AND  GBISJ=''0000'') CM ON CM.MANDT=IFNULL(WB.MANDT,A.RCLNT)  
		AND CM.OBJNR=(CASE WHEN IFNULL(WB.OBJNR,'''')=''''  THEN (CASE WHEN (A.MAT_PSPNR=''00000000'' OR A.MAT_PSPNR<>''00000000'')   THEN  (''PR''||''''||A.MAT_PSPNR) ELSE A.OBJNR  END) ELSE IFNULL(WB.OBJNR,'''') END ) 
		AND IFNULL(H.GJAHR,A.GJAHR)=(CASE WHEN CM.LETJA=''0000'' THEN YEAR(ADD_MONTHS (TO_CHAR (CURRENT_DATE, ''YYYY-MM-DD''), -3)) ELSE CM.LETJA END)

	LEFT JOIN (SELECT * FROM SAPABAP1.COBRB WHERE ANLN1<>'''' AND  GBISJ=''0000'') KA ON  KA.OBJNR=(''PR''||''''||A.MAT_PSPNR) AND A.GJAHR=KA.ERSJA

	LEFT JOIN (SELECT * FROM SAPABAP1.COBRB WHERE ANLN1<>'''' ) CN ON CN.MANDT=IFNULL(WB.MANDT,A.RCLNT)  
		AND CN.OBJNR=(CASE WHEN IFNULL(WB.OBJNR,'''')=''''  THEN (CASE WHEN (A.MAT_PSPNR=''00000000'' OR A.MAT_PSPNR<>''00000000'')   THEN  A.OBJNR ELSE (''PR''||''''||A.MAT_PSPNR)   END) ELSE IFNULL(WB.OBJNR,'''') END ) 
		AND IFNULL(H.GJAHR,A.GJAHR)=(CASE WHEN CN.LETJA=''0000'' THEN YEAR(ADD_MONTHS (TO_CHAR (CURRENT_DATE, ''YYYY-MM-DD''), -3)) ELSE CN.LETJA END)

	LEFT JOIN SAPABAP1.ANLA FI ON IFNULL(IFNULL(CB.BUKRS,IFNULL(CM.BUKRS,CN.BUKRS)),KA.BUKRS)=FI.BUKRS 
		AND (CASE WHEN  IFNULL(CB.ANLN1,'''')='''' AND IFNULL(CN.ANLN1,'''')<>'''' THEN IFNULL(CN.ANLN1,'''') ELSE IFNULL(IFNULL(CB.ANLN1,CM.ANLN1),KA.ANLN1)   END) =FI.ANLN1

	LEFT JOIN (SELECT * FROM SAPABAP1.T095T WHERE  SPRAS=''E'')TA ON TA.MANDT=FI.MANDT AND TA.KTOGR=FI.KTOGR	
	LEFT JOIN SAPABAP1.LFA1 V ON IFNULL(H.LIFNR,A.LIFNR)=V.LIFNR
	LEFT JOIN (SELECT * FROM SAPABAP1.DFKKBPTAXNUM WHERE TAXTYPE=''IN3'') D ON V.LIFNR=D.PARTNER
	LEFT JOIN SAPABAP1.EKPO PO ON L.BUKRS=PO.BUKRS AND L.WERKS=PO.WERKS AND L.EBELN=PO.EBELN AND L.EBELP=PO.EBELP
	LEFT JOIN 
				(
					SELECT
							G.BUKRS COMPANYCODE
							,G.GJAHR FISCALYEAR
							,LEFT(B.AWKEY,10) INVOICENO
							,000||''''||G.TXGRP LINENO
							,G.BUPLA BUSINESSPLACE
							,MAX(G.MWSKZ) TAXCODE
							,MAX(TX.TEXT1) TAXCODEDESC
							,MAX((CASE WHEN G.KSCHL IN (''JICG'') THEN G.HKONT ELSE '''' END))CSGTGLACC
							,MAX((CASE WHEN G.KSCHL IN (''JISG'',''JIUG'') THEN G.HKONT ELSE '''' END))SGSTGLACC
							,MAX((CASE WHEN G.KSCHL IN (''JIIG'') THEN G.HKONT ELSE '''' END))IGSTGLACC
							,MAX((CASE WHEN G.KSCHL IN (''JICG'') THEN G.KBETR/10 ELSE 0.00 END))CGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''JICG'') THEN G.FWSTE ELSE 0.00 END))CGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''JISG'',''JIUG'') THEN G.KBETR/10 ELSE 0.00 END))SGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''JISG'',''JIUG'') THEN G.FWSTE ELSE 0.00 END))SGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''JIIG'') THEN G.KBETR/10 ELSE 0.00 END))IGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''JIIG'') THEN G.FWSTE ELSE 0.00 END))IGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''ZCRN'',''JICR'') THEN ABS(G.KBETR)/10 ELSE 0.00 END))RCMCGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''ZCRN'',''JICR'') THEN G.FWBAS ELSE 0.00 END))RCMCGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''ZSRN'',''JISR'') THEN ABS(G.KBETR)/10 ELSE 0.00 END))RCMSGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''ZSRN'',''JISR'') THEN G.FWBAS ELSE 0.00 END))RCMSGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''ZIRN'',''JIIR'') THEN ABS(G.KBETR)/10 ELSE 0.00 END))RCMIGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''ZIRN'',''JIIR'') THEN G.FWBAS ELSE 0.00 END))RCMIGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''JICN'') THEN G.KBETR/10 ELSE 0.00 END))NDCGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''JICN'') THEN G.FWSTE ELSE 0.00 END))NDCGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''JISN'') THEN G.KBETR/10 ELSE 0.00 END))NDSGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''JISN'') THEN G.FWSTE ELSE 0.00 END))NDSGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''JIIN'') THEN G.KBETR/10 ELSE 0.00 END))NDIGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''JIIN'') THEN G.FWSTE ELSE 0.00 END))NDIGSTAMOUNT
							,MAX(TAX.KBETR) GSTRATE
	
				 FROM SAPABAP1.BSET G
				 LEFT JOIN SAPABAP1.BKPF B ON G.BUKRS=B.BUKRS AND  G.GJAHR=B.GJAHR AND B.BELNR=G.BELNR 
				 LEFT JOIN (SELECT * FROM SAPABAP1.T007S  WHERE MANDT=900 AND SPRAS=''E'' AND KALSM=''TAXINN'') TX ON G.MWSKZ=TX.MWSKZ
				 LEFT JOIN (SELECT V.MWSKZ,SUM(V.KBETR)/10 KBETR FROM SAPABAP1.T007V  V INNER JOIN (SELECT MAX(TRKORR)TRKORR,MWSKZ FROM SAPABAP1.T007V WHERE MANDT=''900'' AND ALAND=''IN'' AND TRKORR LIKE ''G%'' GROUP BY MWSKZ)M ON V.TRKORR=M.TRKORR AND V.MWSKZ=M.MWSKZ
				 WHERE V.KBETR>0 GROUP BY  V.MWSKZ)TAX ON G.MWSKZ=TAX.MWSKZ 
				 WHERE G.MWSKZ  NOT IN (''V0'',''Y0'',''Z0'',''V1'',''V2'',''V3'',''V4'',''V5'',''V6'',''V7'',''V8'')
				GROUP BY 
					G.BUKRS
					,G.GJAHR
					,B.AWKEY
					,G.TXGRP
					,G.BUPLA )GS ON L.BUKRS=GS.COMPANYCODE AND L.GJAHR=GS.FISCALYEAR AND L.BELNR=GS.INVOICENO AND L.BUZEI=GS.LINENO
	LEFT JOIN 
				(SELECT
					E.EBELN ORDERNO 
					,LEFT(M.EXTROW,5)LINENO
					,M.SRVPOS SERVICENO
					,M.KTEXT1 SERVICENAME
					,M.MENGE QTY
					,M.MEINS UOM
					,M.TBTWR RATE
					,M.BASWR AMOUNT
			 FROM SAPABAP1.ESSR E
				LEFT JOIN SAPABAP1.ML_ESLL M ON E.PACKNO=M.HPACKNO AND E.PACKNO=M.FPACKNO
			 WHERE 
				E.KZABN=''X'')S ON L.EBELN=S.ORDERNO AND RIGHT(L.BUZEI,4)||''''||0=S.LINENO
	LEFT JOIN (SELECT * FROM SAPABAP1.T006A WHERE MANDT=900 AND SPRAS=''E'')U ON PO.MEINS=U.MSEHI
	LEFT JOIN (SELECT * FROM SAPABAP1.T006A WHERE MANDT=900 AND SPRAS=''E'')SU ON S.UOM=SU.MSEHI
	LEFT JOIN SAPABAP1.EIPA PR ON L.WERKS=PR.WERKS AND L.EBELN=PR.EBELN AND L.EBELP=PR.EBELP
	LEFT JOIN SAPABAP1.RBCO RB ON L.BUKRS=RB.BUKRS AND L.BELNR=RB.BELNR AND L.GJAHR=RB.GJAHR AND L.BUZEI=RB.BUZEI
	LEFT JOIN (SELECT * FROM SAPABAP1.SKAT WHERE KTOPL=''LGIN'') G ON RB.SAKNR=G.SAKNR
	LEFT JOIN SAPABAP1.ANLA FA ON RB.BUKRS=FA.BUKRS AND RB.ANLN1=FA.ANLN1
	LEFT JOIN SAPABAP1.MARC MA ON L.WERKS=MA.WERKS AND IFNULL(L.MATNR,A.MATNR)=MA.MATNR 
	LEFT JOIN SAPABAP1.MAKT T ON IFNULL(M.MATNR,A.MATNR)=T.MATNR
	LEFT JOIN (SELECT * FROM SAPABAP1.ACDOCA WHERE CO_BELNR LIKE ''A%'' AND BLART=''WA'' AND ACCAS='''') MN ON
		MN.RCLNT=A.RCLNT AND A.RBUKRS=MN.RBUKRS AND A.BELNR=MN.BELNR AND A.AWITEM=MN.AWITEM AND A.GJAHR=MN.AWORG AND A.AWREF=MN.AWREF
	LEFT JOIN SAPABAP1.PRPS WM ON WM.POSID=(CASE WHEN A.MAT_PS_POSID='''' THEN MN.MAT_PS_POSID ELSE A.MAT_PS_POSID END)
	LEFT JOIN SAPABAP1.AFVC AM ON AM.MANDT=A.RCLNT AND AM.BUKRS=A.RBUKRS AND AM.WERKS=A.WERKS AND AM.VORNR=A.NPLNR_VORGN
 WHERE 
	A.CO_BELNR LIKE ''A%''
	AND A.BLART NOT IN (''AA'')
	AND (CASE WHEN  IFNULL(CB.ANLN1,'''')='''' AND IFNULL(CN.ANLN1,'''')<>'''' THEN IFNULL(CN.ANLN1,'''') ELSE IFNULL(CB.ANLN1,CM.ANLN1)   END)<>''''
	AND A.ACCAS<>''''
	AND A.RBUKRS= '''+@COMPANY+'''
	AND A.BUDAT BETWEEN  '''+CONVERT(VARCHAR(10),@FROM_DATE,112)+'''  AND '''+CONVERT(VARCHAR(10),@TO_DATE,112)+'''
UNION ALL 
SELECT  
		A.RBUKRS COMPANY
		,(CASE WHEN IFNULL(A.WERKS,'''')='''' THEN LEFT(A.PRCTR,4) ELSE IFNULL(A.WERKS,'''') END) PLANT
		,PA.NAME1 PLANTNAME
		,A.GJAHR FISCALYEAR
		,IFNULL(A.ANLN1,'''') FIXEDASSET
		,IFNULL(FI.TXT50,'''') FIXEDASSETNAME
		,FI.KTOGR ACCOUNTGROUP
		,TA.KTGRTX ACCOUNTGROUPNAME
		,IFNULL(H.LIFNR,A.LIFNR ) VENDORCODE
		
		,IFNULL((V.NAME1||''''||V.NAME2),'''')VENDORNAME
		,IFNULL(D.TAXNUM,'''') VENDORGSTNUMBER

		,(CASE WHEN V.VEN_CLASS = '''' THEN ''REGISTERED'' ELSE
		 (CASE WHEN V.VEN_CLASS =''0'' THEN ''UNREGISTERED'' ELSE '''' END)END) GSTVENDORTYPE

		,IFNULL(H.PLC_SUP,'''') VENDORSTATECODE
		,IFNULL(L.EBELN,A.EBELN) ORDERNO
		,IFNULL(TO_CHAR(EK.BEDAT,''DD-MON-YYYY''),'''')ORDERDATE
		,IFNULL(M.VGART_MKPF,'''') MATERIALDOCTYPE
		,IFNULL(EKA.LFBNR,'''') MATERIALDOCNO
		,IFNULL((CASE WHEN EKA.BELNR LIKE ''5%'' THEN '''' ELSE EKA.BELNR END),'''') SERVICEENTRYNO
		,(CASE WHEN B.BLART=''RE'' THEN '''' ELSE A.BELNR END) FIMATERIALDOCNO
		,IFNULL(M.MJAHR,'''') FIMMDOCYEAR
		,TO_CHAR(IFNULL(M.BUDAT_MKPF,''''),''DD-MON-YYYY'') MATERIALPOSTINGDATE
		,(CASE WHEN IFNULL(M.BUDAT_MKPF,'''')='''' THEN A.BUDAT ELSE IFNULL(M.BUDAT_MKPF,A.BLDAT) END) MATERIALPOSTDATE

		,(CASE WHEN H.XRECH='''' AND H.TCODE=''MIR7''  THEN ''KG'' ELSE
		 (CASE WHEN H.XRECH='''' AND H.TCODE<>''MIR7''  THEN ''RS'' ELSE IFNULL(B.BLART,A.BLART) END)END) DOCUMENTTYPE

		,(CASE WHEN  H.XRECH<>'''' AND H.TCODE=''MIR7'' THEN ''MM INVOICE''	 ELSE
		 (CASE WHEN  H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ''REVERSE INVOICE'' ELSE
		 (CASE WHEN  IFNULL(B.BLART,'''')=''KR'' THEN ''FI INVOICE'' ELSE
		 (CASE WHEN  IFNULL(B.BLART,'''')=''KG'' THEN ''DEBIT NOTE'' ELSE  
		 (CASE WHEN  IFNULL(B.BLART,A.BLART)=''WE'' THEN ''GOOD RECEIPT'' ELSE  
		 (CASE WHEN  IFNULL(B.BLART,A.BLART)=''AA'' THEN ''ASSET POSTING'' ELSE  IFNULL(B.BLART,'''') END)END)END)END)END)END)DOCUMENTTYPEDESC
		,IFNULL(H.BELNR,'''') INVOICENO
		,IFNULL(B.BELNR,A.BELNR) FIINVOICENO
		,IFNULL(TO_VARCHAR(H.BLDAT,''DD-MON-YYYY''),TO_VARCHAR(A.BLDAT,''DD-MON-YYYY''))  BILLDATE
		,IFNULL(TO_VARCHAR(H.BUDAT,''DD-MON-YYYY''),TO_VARCHAR(A.BUDAT,''DD-MON-YYYY'')) POSTINGDATE
		,IFNULL(IFNULL(H.XBLNR,B.XBLNR),'''') BILLNO

		,(CASE WHEN L.MATNR<>'''' THEN ''GOODS'' ELSE
		 (CASE WHEN IFNULL(RB.ANLN1,'''')<>'''' OR IFNULL(A.ANLN1,'''')<>'''' THEN ''CAPITAL GOODS'' ELSE
		 (CASE WHEN IFNULL(RB.SAKNR,'''')<>'''' OR IFNULL(S.SERVICENO,'''')<>'''' THEN ''SERVICE '' ELSE ''''END)END)END)PURCHASETYPE

		,(CASE WHEN L.MATNR<>'''' THEN ''ITEM'' ELSE
		 (CASE WHEN IFNULL(RB.SAKNR,'''')<>'''' AND IFNULL(RB.ANLN1,'''')='''' OR IFNULL(S.SERVICENO,'''')<>'''' THEN ''GL'' ELSE
		 (CASE WHEN IFNULL(RB.ANLN1,'''')<>'''' OR IFNULL(A.ANLN1,'''')<>'''' THEN ''FIXED ASSET'' ELSE '''' END)END)END) TYPE

		,(CASE WHEN L.MATNR<>'''' THEN IFNULL(T.MAKTX,'''') ELSE
		 (CASE WHEN IFNULL(RB.SAKNR,'''')<>'''' AND IFNULL(RB.ANLN1,'''')='''' OR IFNULL(S.SERVICENO,'''')<>'''' THEN IFNULL(G.TXT50,'''') ELSE
		 (CASE WHEN IFNULL(RB.ANLN1,'''')<>''''   THEN IFNULL(FA.MCOA1,'''') ELSE IFNULL(FI.TXT50,'''')  END)END)END) DESCRIPTION

		,IFNULL(IFNULL(U.MSEHL,SU.MSEHL),(CASE WHEN A.RUNIT='''' THEN ''EA'' ELSE A.RUNIT END) ) UOM
		,IFNULL((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' THEN (CASE WHEN L.MENGE=''0'' THEN 1 ELSE L.MENGE END)*-1 ELSE (CASE WHEN L.MENGE=''0'' THEN 1 ELSE L.MENGE END) END),(CASE WHEN A.MSL=''0.000'' THEN ''1.000'' ELSE A.MSL END)) QUANTITY
		,IFNULL((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' THEN IFNULL(IFNULL(PR.PREIS,S.RATE),PO.NETPR)*-1 ELSE IFNULL(IFNULL(PR.PREIS,S.RATE),PO.NETPR) END),A.HPVPRS) UNITCOST
		,(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' THEN A.HSL*-1 ELSE A.HSL END)  SETTLEMENTAMOUNT
		,(CASE WHEN IFNULL(L.WRBTR,0.00)=0.00 THEN A.HSL ELSE IFNULL(L.WRBTR,0.00) END)  INVOICEAMT
		,IFNULL(GS.TAXCODE,'''')TAXCODE
		,IFNULL(GS.TAXCODEDESC,'''')TAXCODEDESC
		,CAST(IFNULL(GS.GSTRATE,0.00) AS NUMERIC(18,3))GSTRATE
		,(CASE WHEN
				 ((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.CGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.CGSTAMOUNT,0.00) END)+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.SGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.SGSTAMOUNT,0.00) END) +(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.IGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.IGSTAMOUNT,0.00) END))=0 AND 
				((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMCGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMCGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMSGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMSGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMIGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMIGSTAMOUNT,0.00)) END))=0
			THEN 
				(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.NDCGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.NDCGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.NDSGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.NDSGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN  ABS(IFNULL(GS.NDIGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.NDIGSTAMOUNT,0.00)) END)
			 ELSE 
			 (CASE WHEN 
				((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.CGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.CGSTAMOUNT,0.00) END)+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.SGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.SGSTAMOUNT,0.00) END) +(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.IGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.IGSTAMOUNT,0.00) END))<>0 THEN 
				(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.CGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.CGSTAMOUNT,0.00) END)+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.SGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.SGSTAMOUNT,0.00) END) +(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN IFNULL(GS.IGSTAMOUNT,0.00)*-1 ELSE IFNULL(GS.IGSTAMOUNT,0.00) END) ELSE
			 (CASE WHEN 
				((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMCGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMCGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMSGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMSGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMIGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMIGSTAMOUNT,0.00)) END)) <>0 THEN 
				((CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMCGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMCGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMSGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMSGSTAMOUNT,0.00)) END)
				+(CASE WHEN H.VGART=''RS'' AND H.XRECH='''' AND H.TCODE<>''MIR7'' THEN ABS(IFNULL(GS.RCMIGSTAMOUNT,0.00))*-1 ELSE ABS(IFNULL(GS.RCMIGSTAMOUNT,0.00)) END))
			 ELSE 0 END)END)END) TOTALGST
		,A.CO_BELNR SETTLEMENTNO
			,'''' NETWORK
		,'''' NETWORKNAME
		,'''' ACTIVITY
		,'''' ACTIVITYNAME
		,'''' ACCOUNTASSIGNMENT
		,'''' WBSELEMENT
		,'''' WBSELEMENTNAME
		,'''' POSID
		,A.SGTXT REMARK
		,EP.TXZ01 SHORTTEXT
		,A.ANBWA
FROM SAPABAP1.ACDOCA A
	LEFT JOIN SAPABAP1.EKPO EP ON EP.BUKRS=A.RBUKRS AND EP.EBELN=A.EBELN AND EP.EBELP=A.EBELP
	LEFT JOIN SAPABAP1.EKKO EK ON EK.BUKRS=A.RBUKRS AND EK.EBELN=A.EBELN
	LEFT JOIN SAPABAP1.T001W PA ON PA.WERKS=(CASE WHEN IFNULL(A.WERKS,'''')='''' THEN LEFT(A.PRCTR,4) ELSE IFNULL(A.WERKS,'''') END)
	LEFT JOIN SAPABAP1.NSDM_V_MSEG MS ON  MS.EBELN=A.EBELN AND MS.EBELP=A.EBELP AND A.AWORG=MS.MJAHR AND A.AWREF=MS.MBLNR AND A.AWITEM=MS.LINE_ID
	LEFT JOIN (SELECT * FROM SAPABAP1.EKBE WHERE BEWTP IN (''Q'',''T'')) EKA ON MS.EBELN=EKA.EBELN AND MS.EBELP=EKA.EBELP AND MS.LFBJA=EKA.LFGJA AND MS.LFBNR=EKA.LFBNR AND MS.LFPOS=EKA.LFPOS
	LEFT JOIN (SELECT * FROM SAPABAP1.RBKP WHERE RBSTAT=''5'') H ON H.BELNR=EKA.BELNR AND H.GJAHR=EKA.GJAHR
	LEFT JOIN (SELECT * FROM SAPABAP1.BKPF WHERE BLART IN (''RE'',''KR'',''KG'')) B ON B.BELNR=A.BELNR AND B.GJAHR=A.GJAHR AND A.RBUKRS=B.BUKRS	
	LEFT JOIN SAPABAP1.RSEG L ON H.BUKRS=L.BUKRS AND H.BELNR=L.BELNR AND H.GJAHR=L.GJAHR AND EKA.EBELN=L.EBELN AND EKA.EBELP=L.EBELP AND EKA.LFGJA=L.LFGJA AND EKA.LFBNR=L.LFBNR AND EKA.LFPOS=L.LFPOS
	LEFT JOIN SAPABAP1.NSDM_V_MSEG M ON  M.EBELN=IFNULL(L.EBELN,A.EBELN) AND M.EBELP=IFNULL(L.EBELP,A.EBELP) AND IFNULL(L.LFGJA,A.AWORG)=M.MJAHR AND IFNULL(L.LFBNR,A.AWREF)=M.MBLNR AND IFNULL(L.LFPOS,A.AWITEM)=(CASE WHEN IFNULL(L.LFPOS,'''')='''' THEN M.LINE_ID ELSE M.ZEILE END)
	LEFT JOIN SAPABAP1.ANLA FI ON A.RBUKRS=FI.BUKRS AND A.ANLN1=FI.ANLN1
	LEFT JOIN (SELECT * FROM SAPABAP1.T095T WHERE  SPRAS=''E'')TA ON TA.MANDT=FI.MANDT AND TA.KTOGR=FI.KTOGR	
	LEFT JOIN SAPABAP1.LFA1 V ON (CASE WHEN IFNULL(H.LIFNR,A.LIFNR )='''' THEN A.GKONT ELSE IFNULL(H.LIFNR,A.LIFNR ) END)=V.LIFNR
	LEFT JOIN (SELECT * FROM SAPABAP1.DFKKBPTAXNUM WHERE TAXTYPE=''IN3'') D ON V.LIFNR=D.PARTNER
	LEFT JOIN SAPABAP1.EKPO PO ON L.BUKRS=PO.BUKRS AND L.WERKS=PO.WERKS AND L.EBELN=PO.EBELN AND L.EBELP=PO.EBELP
	LEFT JOIN 
				(
					SELECT
							G.BUKRS COMPANYCODE
							,G.GJAHR FISCALYEAR
							,(CASE WHEN B.BLART IN (''KR'',''KG'',''KA'') THEN B.BELNR  ELSE LEFT(B.AWKEY,10) END) INVOICENO
							,000||''''||G.TXGRP LINENO
							,G.BUPLA BUSINESSPLACE
							,MAX(G.MWSKZ) TAXCODE
							,MAX(TX.TEXT1) TAXCODEDESC
							,MAX((CASE WHEN G.KSCHL IN (''JICG'') THEN G.HKONT ELSE '''' END))CSGTGLACC
							,MAX((CASE WHEN G.KSCHL IN (''JISG'',''JIUG'') THEN G.HKONT ELSE '''' END))SGSTGLACC
							,MAX((CASE WHEN G.KSCHL IN (''JIIG'') THEN G.HKONT ELSE '''' END))IGSTGLACC
							,MAX((CASE WHEN G.KSCHL IN (''JICG'') THEN G.KBETR/10 ELSE 0.00 END))CGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''JICG'') THEN G.FWSTE ELSE 0.00 END))CGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''JISG'',''JIUG'') THEN G.KBETR/10 ELSE 0.00 END))SGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''JISG'',''JIUG'') THEN G.FWSTE ELSE 0.00 END))SGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''JIIG'') THEN G.KBETR/10 ELSE 0.00 END))IGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''JIIG'') THEN G.FWSTE ELSE 0.00 END))IGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''ZCRN'',''JICR'') THEN ABS(G.KBETR)/10 ELSE 0.00 END))RCMCGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''ZCRN'',''JICR'') THEN G.FWBAS ELSE 0.00 END))RCMCGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''ZSRN'',''JISR'') THEN ABS(G.KBETR)/10 ELSE 0.00 END))RCMSGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''ZSRN'',''JISR'') THEN G.FWBAS ELSE 0.00 END))RCMSGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''ZIRN'',''JIIR'') THEN ABS(G.KBETR)/10 ELSE 0.00 END))RCMIGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''ZIRN'',''JIIR'') THEN G.FWBAS ELSE 0.00 END))RCMIGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''JICN'') THEN G.KBETR/10 ELSE 0.00 END))NDCGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''JICN'') THEN G.FWSTE ELSE 0.00 END))NDCGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''JISN'') THEN G.KBETR/10 ELSE 0.00 END))NDSGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''JISN'') THEN G.FWSTE ELSE 0.00 END))NDSGSTAMOUNT
							,MAX((CASE WHEN G.KSCHL IN (''JIIN'') THEN G.KBETR/10 ELSE 0.00 END))NDIGSTRATE
							,SUM((CASE WHEN G.KSCHL IN (''JIIN'') THEN G.FWSTE ELSE 0.00 END))NDIGSTAMOUNT
							,MAX(TAX.KBETR) GSTRATE
	
				 FROM SAPABAP1.BSET G
				 LEFT JOIN SAPABAP1.BKPF B ON G.BUKRS=B.BUKRS AND  G.GJAHR=B.GJAHR AND B.BELNR=G.BELNR 
				 LEFT JOIN (SELECT * FROM SAPABAP1.T007S  WHERE MANDT=900 AND SPRAS=''E'' AND KALSM=''TAXINN'') TX ON G.MWSKZ=TX.MWSKZ
				 LEFT JOIN (SELECT V.MWSKZ,SUM(V.KBETR)/10 KBETR FROM SAPABAP1.T007V  V INNER JOIN (SELECT MAX(TRKORR)TRKORR,MWSKZ FROM SAPABAP1.T007V WHERE MANDT=''900'' AND ALAND=''IN'' AND TRKORR LIKE ''G%'' GROUP BY MWSKZ)M ON V.TRKORR=M.TRKORR AND V.MWSKZ=M.MWSKZ
				 WHERE V.KBETR>0 GROUP BY  V.MWSKZ)TAX ON G.MWSKZ=TAX.MWSKZ 
				 WHERE G.MWSKZ  NOT IN (''V0'',''Y0'',''Z0'',''V1'',''V2'',''V3'',''V4'',''V5'',''V6'',''V7'',''V8'')
				GROUP BY 
					G.BUKRS
					,G.GJAHR
					,B.AWKEY
					,G.TXGRP
					,B.BLART
					,B.BELNR
					,G.BUPLA )GS ON IFNULL(L.BUKRS,A.RBUKRS)=GS.COMPANYCODE AND IFNULL(L.GJAHR,A.GJAHR)=GS.FISCALYEAR AND IFNULL(L.BELNR,A.BELNR)=GS.INVOICENO AND IFNULL(L.BUZEI,A.DOCLN)=GS.LINENO
	LEFT JOIN 
				(SELECT
					E.EBELN ORDERNO 
					,LEFT(M.EXTROW,5)LINENO
					,M.SRVPOS SERVICENO
					,M.KTEXT1 SERVICENAME
					,M.MENGE QTY
					,M.MEINS UOM
					,M.TBTWR RATE
					,M.BASWR AMOUNT
			 FROM SAPABAP1.ESSR E
				LEFT JOIN SAPABAP1.ML_ESLL M ON E.PACKNO=M.HPACKNO AND E.PACKNO=M.FPACKNO
			 WHERE 
				E.KZABN=''X'')S ON L.EBELN=S.ORDERNO AND RIGHT(L.BUZEI,4)||''''||0=S.LINENO
	LEFT JOIN (SELECT * FROM SAPABAP1.T006A WHERE MANDT=900 AND SPRAS=''E'')U ON PO.MEINS=U.MSEHI
	LEFT JOIN (SELECT * FROM SAPABAP1.T006A WHERE MANDT=900 AND SPRAS=''E'')SU ON S.UOM=SU.MSEHI
	LEFT JOIN SAPABAP1.EIPA PR ON L.WERKS=PR.WERKS AND L.EBELN=PR.EBELN AND L.EBELP=PR.EBELP
	LEFT JOIN SAPABAP1.RBCO RB ON L.BUKRS=RB.BUKRS AND L.BELNR=RB.BELNR AND L.GJAHR=RB.GJAHR AND L.BUZEI=RB.BUZEI AND A.ANLN1=RB.ANLN1
	LEFT JOIN (SELECT * FROM SAPABAP1.SKAT WHERE KTOPL=''LGIN'') G ON RB.SAKNR=G.SAKNR
	LEFT JOIN SAPABAP1.ANLA FA ON RB.BUKRS=FA.BUKRS AND RB.ANLN1=FA.ANLN1
	LEFT JOIN SAPABAP1.MARC MA ON L.WERKS=MA.WERKS AND L.MATNR=MA.MATNR 
	LEFT JOIN SAPABAP1.MAKT T ON L.MATNR=T.MATNR
 WHERE 
   A.KOART=''A''
    AND A.GKOAR LIKE (CASE WHEN  A.BTTYPE=''ABGA'' THEN ''S%'' ELSE ''%'' END)
	AND A.ANBWA IN (''100'',''101'',''105'',''120'',''160'',''340'',''345'',''320'',''330'',''130'',''341'',''346'',''260'')
	AND A.XSECONDARY=(CASE WHEN A.BTTYPE=''ABGA'' THEN ''X'' ELSE '''' END)	
)K
WHERE K.COMPANY LIKE '''+@COMPANY+'''
AND K.MATERIALPOSTDATE BETWEEN '''+CONVERT(VARCHAR(10),@FROM_DATE,112)+'''  AND '''+CONVERT(VARCHAR(10),@TO_DATE,112)+'''
' + ISNULL(@ASSETNO, ' ') + '

'
--Select @SQL=@SQL1+@SQL2
PRINT (@SQL)
EXEC(@SQL) AT SAP_GHP









