USE [SAPCONNECT]
GO
/****** Object:  StoredProcedure [dbo].[SAP_VENDOR_PO_PAYMENT_EXCEL]    Script Date: 03-07-2024 10:32:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--[SAP_VENDOR_PO_PAYMENT] '1000000069'
ALTER PROCEDURE [dbo].[SAP_VENDOR_PO_PAYMENT_EXCEL] 
(
	@COMPANY VARCHAR(10)= '%'
	,@PLANT VARCHAR(MAX) = '%'
	,@FROM_DATE DATETIME
	,@TO_DATE DATETIME
	,@PURGROUP VARCHAR(MAX)='%'
)
AS
BEGIN

--SAP_VENDOR_PO_PAYMENT_EXCEL '12','1203','20170401','20200819',''


IF @PLANT IN ('ALL' ,'','%','''')
	BEGIN
		SET @PLANT=NULL
	END	
ELSE
	SELECT @PLANT = ' AND ''' + @PLANT + ''' LIKE ''%'' || NULLIF(K.PLANT ,'''') || ''%'' '

IF @PURGROUP IN ('ALL' ,'','%','''')
	BEGIN
		SET @PURGROUP=NULL
	END
ELSE
	SELECT @PURGROUP = ' AND ''' + @PURGROUP + ''' LIKE ''%'' || NULLIF(K.PURCHASEGROUP,'''') || ''%'' '

DECLARE @SQL VARCHAR(MAX)
DECLARE @SQL1 VARCHAR(MAX)
DECLARE @SQL2 VARCHAR(MAX)
DECLARE @chr AS varchar(1)= CHAR(13)

SELECT @SQL1=
'SELECT ROW_NUMBER() OVER (ORDER BY K.COMPANYCODE,K.PLANT,K.ORDERNO) SRNO' 
+ @chr +'	,K.COMPANYCODE'
+ @chr +'	,K.PLANT'
+ @chr +'	,K.PLANTNAME PLANT_NAME'
+ @chr +'	,K.PURCHASEGROUP'
+ @chr +'	,K.PURCHASEGROUP_NAME'
+ @chr +'	,K.NETWORK'
+ @chr +'	,K.NETWORKNAME'
+ @chr +'	,K.ACTIVITY'
+ @chr +'	,K.ACTIVITYNAME'
+ @chr +'	,K.WBSELEMENT'
+ @chr +'	,K.WBSELEMENTNAME'
+ @chr +'	,K.POSID'
+ @chr +'	,K.VENDORNO VENDOR_NO'
+ @chr +'	,K.VENDORNAME VENDOR_NAME'
+ @chr +'	,K.VENDORCATEGORY'
+ @chr +'	,K.ADD1||''''||K.ADD2||''''||K.ADD3 VENDOR_ADDRESS'
+ @chr +'	,K.CITY'
+ @chr +'	,K.POSTCODE'
+ @chr +'	,K.VENDOREMAIL VENDOR_EMAIL'
+ @chr +'	,K.VENDORGSTNUMBER VENDOR_GST_NO'
+ @chr +'	,K.MOBILENO VENDOR_CONTACT_NO'
+ @chr +'	,K.PANNO VENDOR_PAN_NO'
+ @chr +'	,K.ORDERNO PURCHASE_ORDER_NO'
+ @chr +'	,K.ORDERDATE PURCHASE_ORDER_DATE'
+ @chr +'	,K.SHORTTEXT SHORT_TEXT'
+ @chr +'	,(Case when K.Ordersrno=1 then K.ORDERVALUE else 0 end) PURCHASE_ORDER_VALUE'
+ @chr +'	,K.FIINVOICENO LEDGER_INV_NO'
+ @chr +'	,K.INVOICENO'
+ @chr +'	,K.INVOICEDATE BILL_DATE'
+ @chr +'	,K.BILLNO BILL_NO'
+ @chr +'	,K.INVOICEPOSTDATE INVOICE_POSTING_DATE'
+ @chr +'   ,K.REEWR INVOICE_GROSS_AMOUNT '
+ @chr +'	,(Case when K.Invoicesrno=1 then (K.RMWWR-(CASE WHEN IFNULL(TD.TDSAMT,0.00)=0 THEN IFNULL(MN.TDSAMOUNT,0.00) ELSE IFNULL(TD.TDSAMT,0.00) END))  else 0 end)INVOICE_AMOUNT'
+ @chr +'	,(Case when K.Invoicesrno=1 then IFNULL(K.BEZNK,0.00) else 0 end) FREIGHTAMT'
+ @chr +'	,(Case when K.Invoicesrno=1 then IFNULL(K.WMWST1,0.00) else 0 end)GSTAMOUNT'
+ @chr +'	,(Case when K.Invoicesrno=1 then (CASE WHEN IFNULL(TD.TDSAMT,0.00)=0 THEN IFNULL(MN.TDSAMOUNT,0.00) ELSE IFNULL(TD.TDSAMT,0.00) END) else 0 end)TDSAMOUNT'
+ @chr +'	,K.INVOICEFISCALYEAR'
+ @chr +'	,(CASE WHEN (K.RMWWR-(CASE WHEN IFNULL(TD.TDSAMT,0.00)=0 THEN IFNULL(MN.TDSAMOUNT,0.00) ELSE (CASE WHEN IFNULL(TD.TDSAMT,0.00)=0 THEN IFNULL(MN.TDSAMOUNT,0.00) ELSE IFNULL(TD.TDSAMT,0.00) END) END))-IFNULL((IFNULL(PP.WRBTR,ABS(BL.AMOUNT))),0.00)=0 AND K.DOWNPAYMENT=0 THEN ''PAID'' ELSE '
+ @chr +'	 (CASE WHEN (K.RMWWR-(CASE WHEN IFNULL(TD.TDSAMT,0.00)=0 THEN IFNULL(MN.TDSAMOUNT,0.00) ELSE (CASE WHEN IFNULL(TD.TDSAMT,0.00)=0 THEN IFNULL(MN.TDSAMOUNT,0.00) ELSE IFNULL(TD.TDSAMT,0.00) END) END))-IFNULL((IFNULL(PP.WRBTR,ABS(BL.AMOUNT))),0.00)=0 AND K.DOWNPAYMENT<>0 THEN ''ADVANCE PAID'' ELSE '
+ @chr +'	 (CASE WHEN IFNULL((IFNULL(PP.WRBTR,ABS(BL.AMOUNT))),0.00)<>0 AND (K.RMWWR-(CASE WHEN IFNULL(TD.TDSAMT,0.00)=0 THEN IFNULL(MN.TDSAMOUNT,0.00) ELSE (CASE WHEN IFNULL(TD.TDSAMT,0.00)=0 THEN IFNULL(MN.TDSAMOUNT,0.00) ELSE IFNULL(TD.TDSAMT,0.00) END) END))-IFNULL((IFNULL(PP.WRBTR,ABS(BL.AMOUNT))),0.00)<>0 THEN ''PARTIALY PAID'' ELSE '
+ @chr +'		K.INVOICESTATUS END)END)END) INVOICE_STATUS	'
+ @chr +'	 ,(Case when K.Invoicesrno=1 then IFNULL((IFNULL(PP.WRBTR,ABS(BL.AMOUNT))),0.00) else 0 end) PAID_AMOUNT'
+ @chr +'	 ,(Case when K.Invoicesrno=1 then ((K.RMWWR-(CASE WHEN IFNULL(TD.TDSAMT,0.00)=0 THEN IFNULL(MN.TDSAMOUNT,0.00) ELSE IFNULL(TD.TDSAMT,0.00) END))-IFNULL((IFNULL(PP.WRBTR,ABS(BL.AMOUNT))),0.00)) else 0 end) BALANCEAMOUNT '
+ @chr +'	 ,K.HEADERTEXT '
+ @chr +'	 ,K.ENTERYDATE '
+ @chr +'	 ,K.PARKEDDATE '
+ @chr +'	 ,U.USERNAME PARKEDBY '
+ @chr +'	 ,K.ORDERPOSTINGDATE POSTINGDATE '
+ @chr +' FROM  '
+ @chr +'( '
+ @chr +'SELECT  '
+ @chr +'	EK.BUKRS COMPANYCODE '
+ @chr +'	,P.WERKS PLANT '
+ @chr +'	,PA.NAME1 PLANTNAME '
+ @chr +'	,EK.LIFNR VENDORNO '
+ @chr +'	,(V.NAME1||''''||V.NAME2||''''||V.NAME3)VENDORNAME '
+ @chr +'	,V.KONZS VENDORCATEGORY '
+ @chr +'	,A.STREET||''''||A.STR_SUPPL1 ADD1 '
+ @chr +'	,A.STR_SUPPL2 ADD2 '
+ @chr +'	,A.STR_SUPPL3 ADD3 '
+ @chr +'	,V.STRAS ADD4 '
+ @chr +'	,A.CITY1 CITY '
+ @chr +'	,A.POST_CODE1 POSTCODE '
+ @chr +'	,IFNULL(ADS.SMTP_ADDR,'''')VENDOREMAIL '
+ @chr +'	,IFNULL(D.TAXNUM,'''') VENDORGSTNUMBER '
+ @chr +'	,V.TELF1 MOBILENO '
+ @chr +'	,V.J_1IPANNO PANNO '
+ @chr +'	,EK.EBELN ORDERNO '
+ @chr +'	,EK.PINCR ORDERLINENO '
+ @chr +'	,TO_CHAR(EK.BEDAT,''DD/MM/YYYY'')ORDERDATE '
+ @chr +'	,EK.BEDAT ORDERPOSTINGDATE '
+ @chr +'	,EP.TXZ01 SHORTTEXT '
+ @chr +'	,EK.RLWRT ORDERVALUE '
+ @chr +'	,P.BELNR INVOICENO ' --ekbe
+ @chr +'	,IFNULL(B.XBLNR,'''') BILLNO '
+ @chr +'	,IFNULL(TO_CHAR(P.BUDAT,''DD/MM/YYYY''),'''')INVOICEPOSTDATE '
+ @chr +'	,P.BUDAT POSTINGDATE '
+ @chr +'	,IFNULL(P.WRBTR,0.00) INVOICEAMOUNT '
+ @chr +'   ,P.REEWR'
+ @chr +'	,B.GJAHR INVOICEFISCALYEAR '
+ @chr +'	,(CASE WHEN P.BEWTP=''Q'' THEN ''POSTED'' ELSE ''PARKED'' END)INVOICESTATUS '
+ @chr +'	,IFNULL(TO_CHAR(B.BLDAT,''DD/MM/YYYY''),'''')INVOICEDATE '
+ @chr +'	,B.BELNR FIINVOICENO ' --bkpf
+ @chr +'	,B.BKTXT HEADERTEXT '
+ @chr +'	,IFNULL(TO_CHAR(B.CPUDT,''DD/MM/YYYY''),'''') ENTERYDATE '
+ @chr +'	,IFNULL(TO_CHAR(B.PPDAT,''DD/MM/YYYY''),'''') PARKEDDATE '
+ @chr +'	,B.PPNAM PARKBY '
+ @chr +'	,EK.DPAMT DOWNPAYMENT '
+ @chr +'	,EK.EKGRP PURCHASEGROUP  '
+ @chr +'	,TO.EKNAM PURCHASEGROUP_NAME '
+ @chr +'	,IFNULL(ME.NPLNR,'''') NETWORK'
+ @chr +'	,IFNULL(PN.KTEXT,'''') NETWORKNAME'
+ @chr +'	,IFNULL(AF.VORNR,'''') ACTIVITY'
+ @chr +'	,IFNULL(AF.LTXA1,'''') ACTIVITYNAME'
+ @chr +'	,IFNULL(WB.POSKI,'''') WBSELEMENT'
+ @chr +'	,IFNULL(WB.POST1,'''') WBSELEMENTNAME'
+ @chr +'	,IFNULL(WB.POSID,'''') POSID'
+ @chr +'	,RP.RMWWR '
+ @chr +'	,RP.BEZNK '
+ @chr +'	,RP.WMWST1 '
+ @chr +'	,Row_number() Over(Partition by EK.BUKRS,P.Werks,EK.LIFNR,EK.EBELN order by EK.BUKRS,P.Werks,EK.LIFNR,EK.EBELN)Ordersrno '
+ @chr +'	,Row_number() Over(Partition by EK.BUKRS,P.Werks,EK.LIFNR,P.BELNR,B.GJAHR order by EK.BUKRS,P.Werks,EK.LIFNR,P.BELNR,B.GJAHR)Invoicesrno '
+ @chr +' FROM SAPABAP1.EKKO EK '
+ @chr +'	LEFT JOIN SAPABAP1.T024 TO ON EK.EKGRP=TO.EKGRP '
+ @chr +'	LEFT JOIN (SELECT * FROM SAPABAP1.EKBE WHERE BEWTP IN (''Q'',''T'')) P ON EK.BUKRS=LEFT(P.WERKS,2) AND EK.EBELN=P.EBELN '
+ @chr +'	LEFT JOIN SAPABAP1.EKPO EP ON EP.BUKRS=LEFT(P.WERKS,2) AND EP.EBELN=P.EBELN AND EP.EBELP=P.EBELP '
+ @chr +'	LEFT JOIN (select * from SAPABAP1.BKPF where DOCCAT=''INVREC'')  B ON P.BELNR=LEFT(B.AWKEY,10) AND P.GJAHR=B.GJAHR AND LEFT(P.WERKS,2)=B.BUKRS AND B.BLART=''RE'' '
+ @chr +'	LEFT JOIN SAPABAP1.LFA1 V ON EK.LIFNR=V.LIFNR '
+ @chr +'	LEFT JOIN SAPABAP1.ADRC  A ON V.ADRNR=A.ADDRNUMBER '
+ @chr +'	LEFT JOIN (SELECT ADDRNUMBER,MAX(SMTP_ADDR)SMTP_ADDR FROM SAPABAP1.ADR6 GROUP BY ADDRNUMBER) ADS ON V.ADRNR=ADS.ADDRNUMBER '
+ @chr +'	LEFT JOIN (SELECT * FROM SAPABAP1.DFKKBPTAXNUM WHERE TAXTYPE=''IN3'') D ON V.LIFNR=D.PARTNER '
+ @chr +'	LEFT JOIN SAPABAP1.T001W PA ON PA.WERKS=P.WERKS '
+ @chr +'   LEFT JOIN SAPABAP1.RBKP RP ON  P.GJAHR=RP.GJAHR AND P.BELNR=RP.BELNR '
+ @chr +'   LEFT JOIN (SELECT DISTINCT MANDT,BUKRS,WERKS,AUFPL,APLZL,EBELN,EBELP,NPLNR,PS_PSP_PNR FROM SAPABAP1.NSDM_V_MSEG) ME ON  ME.EBELN=EK.EBELN AND ME.EBELP=EK.PINCR  '
+ @chr +'   LEFT JOIN SAPABAP1.AFVC AF ON  AF.AUFPL=ME.AUFPL AND AF.APLZL=ME.APLZL AND AF.MANDT=ME.MANDT AND AF.BUKRS=ME.BUKRS AND AF.WERKS=ME.WERKS '
+ @chr +'   LEFT JOIN SAPABAP1.M_AUKOB PN ON PN.AUFNR=ME.NPLNR '
+ @chr +'   LEFT JOIN SAPABAP1.PRPS WB ON WB.PSPNR=(CASE WHEN IFNULL(AF.PROJN,'''')='''' THEN ME.PS_PSP_PNR ELSE AF.PROJN END) '

+ @chr +')K  '


+ @chr +' LEFT JOIN  '
+ @chr +'	( '
+ @chr +'		SELECT BUKRS,BELNR,GJAHR,WT_ACCO,ABS(SUM(WT_QBSHH))TDSAMT,ABS(SUM(WT_QSSHH))TDSBASEAMT '
+ @chr +'	FROM SAPABAP1.WITH_ITEM WHERE WT_QBSHH<>0 '
+ @chr +'	GROUP BY BUKRS,BELNR,GJAHR,WT_ACCO)TD ON K.COMPANYCODE=TD.BUKRS AND K.INVOICEFISCALYEAR=TD.GJAHR AND K.FIINVOICENO=TD.BELNR AND K.VENDORNO=TD.WT_ACCO '

+ @chr +'LEFT JOIN ( '
+ @chr +'	SELECT  '
+ @chr +'		B.BUKRS '
+ @chr +'		,B.BELNR '
+ @chr +'		,B.GJAHR '
+ @chr +'		,ABS(IFNULL(SUM((CASE WHEN B.SHKZG=''S'' THEN B.WRBTR ELSE B.WRBTR*-1 END)),0.00))TDSAMOUNT  '
+ @chr +'		,IFNULL(SUM(S.WRBTR),0.00)TDSBASAMOUNT '
+ @chr +'	FROM SAPABAP1.BSEG B '
+ @chr +'		LEFT JOIN (SELECT * FROM SAPABAP1.BSEG WHERE QSSKZ=''XX'')S ON B.BUKRS=S.BUKRS AND B.GJAHR=S.GJAHR AND B.BELNR=S.BELNR '
+ @chr +'	WHERE  '
+ @chr +'			B.KTOSL=''WIT'' '
+ @chr +' GROUP BY B.BUKRS,B.BELNR,B.GJAHR)MN ON K.COMPANYCODE=MN.BUKRS AND K.INVOICEFISCALYEAR=MN.GJAHR AND K.BLDAT=MN.BELNR '

+ @chr +'LEFT JOIN  '
+ @chr +'	(SELECT BUKRS,LIFNR,REBZG,REBZJ,SUM(WRBTR) WRBTR FROM SAPABAP1.BSIK WHERE REBZG<>'''' GROUP BY BUKRS,LIFNR,REBZG,REBZJ)PP ON  '
+ @chr +'	K.COMPANYCODE=PP.BUKRS AND K.INVOICEFISCALYEAR=PP.REBZJ AND K.FIINVOICENO=PP.REBZG AND K.VENDORNO=PP.LIFNR '

+ @chr +'LEFT JOIN (SELECT BUKRS,GJAHR,BELNR,SUM((CASE WHEN SHKZG=''S'' THEN IFNULL(WRBTR,0.00) ELSE IFNULL(WRBTR,0.00)*-1 END))AMOUNT FROM SAPABAP1.BSAK GROUP BY BUKRS,GJAHR,BELNR)BL ON  '
+ @chr +'	K.COMPANYCODE=BL.BUKRS AND K.INVOICEFISCALYEAR=BL.GJAHR AND K.FIINVOICENO=BL.BELNR  '
+ @chr +'LEFT JOIN  '
+ @chr +'	(SELECT A.BNAME USERID,T.NAME_TEXT USERNAME FROM SAPABAP1.V_ADDR_USR T '
+ @chr +'			INNER JOIN (SELECT * FROM SAPABAP1.USR21 WHERE MANDT=900) A ON T.PERSNUMBER=A.PERSNUMBER)U ON K.PARKBY=U.USERID '
+ @chr +' WHERE  '
+ @chr +'	 K.COMPANYCODE= ''' + @COMPANY + ''' '
			+ ISNULL(@PLANT, ' ') 
+ @chr +'	AND K.ORDERPOSTINGDATE BETWEEN ''' + CONVERT(VARCHAR(10),@FROM_DATE,112) + '''  AND ''' + CONVERT(VARCHAR(10),@TO_DATE,112) + ''' '
		 + ISNULL(@PURGROUP, ' ') 
select @SQL2=

+ @chr +' ORDER BY K.COMPANYCODE,K.PLANT,K.ORDERPOSTINGDATE,K.VENDORNO,K.ORDERNO   '


select @SQL=@SQL1+@SQL2
PRINT @SQL	
EXEC(@SQL) AT SAP_GHP


END